# Generated by Django 4.2.1 on 2023-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tvideo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichier",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="fichier",
            name="fichier",
        ),
        migrations.AddField(
            model_name="fichier",
            name="fichier_audio",
            field=models.FileField(
                default="default_audio.mp3", upload_to="staticfiles/audio/"
            ),
        ),
    ]
