# Generated by Django 4.2.1 on 2023-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tvideo", "0002_remove_fichier_date_creation_remove_fichier_fichier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichier",
            name="fichier_audio",
            field=models.FileField(upload_to="audio/"),
        ),
    ]
