# Generated by Django 4.2.1 on 2023-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tvideo", "0003_alter_fichier_fichier_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichier",
            name="fichier_video",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
        migrations.AlterField(
            model_name="fichier",
            name="fichier_audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
