# Generated by Django 4.2.1 on 2023-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tvideo", "0004_fichier_fichier_video_alter_fichier_fichier_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichier",
            name="fichier_audio",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="fichier",
            name="fichier_video",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
